version: "3.7"

# due to: https://docs.docker.com/compose/startup-order/

services:
  postgres:
    restart: always
    image: postgres:14-alpine
    container_name: "postgres"
    env_file: mastodon.env
    healthcheck:
      #test: pg_isready -U postgres   
      test: ["CMD", "psql mastodon", "-c", "select now();"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - "./mastodon/postgres:/var/lib/postgresql/data"
      #- "./mastodon.sql:/docker-entrypoint-initdb.d/seed.sql"
